// front/src/lib/components/CashDisplay.svelte
<script lang="ts">
	import { untrack } from 'svelte';

	let { cash }: { cash: number } = $props();

	let prev: number | undefined = $state(undefined);
	let delta: number | null = $state(null);
	let timer: ReturnType<typeof setTimeout> | undefined = undefined;

	$effect(() => {
		const current = cash;
		const old = untrack(() => prev);
		if (old === undefined) {
			untrack(() => {
				prev = current;
			});
			return;
		}
		if (current === old) return;
		untrack(() => {
			prev = current;
		});
		delta = current - old;
		clearTimeout(timer);
		timer = setTimeout(() => {
			delta = null;
		}, 2400);
		return () => clearTimeout(timer);
	});

	const fmt = (n: number) => n.toLocaleString('en-US');
	const gain = $derived(delta !== null && delta > 0);
	const loss = $derived(delta !== null && delta < 0);
</script>

<span class="inline-flex items-center gap-1.5 font-mono">
	<span
		class="font-semibold transition-colors {gain
			? 'text-green-700'
			: loss
				? 'text-red-700'
				: 'text-slate-800'}"
	>
		৳{fmt(cash)}
	</span>
	{#if delta !== null && delta !== 0}
		<span
			class="anim-log-in rounded-full px-1.5 text-xs font-bold {gain
				? 'bg-green-100 text-green-800'
				: 'bg-red-100 text-red-800'}"
		>
			{gain ? `+${fmt(delta)}` : fmt(delta)}
		</span>
	{/if}
</span>

// web/src/lib/components/CashDisplay.tsx
'use client';

import { useEffect, useRef, useState } from 'react';

export default function CashDisplay({ cash }: { cash: number }) {
	const [prev, setPrev] = useState(cash);
	const [delta, setDelta] = useState<number | null>(null);
	const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

	useEffect(() => {
		if (cash === prev) return;
		setDelta(cash - prev);
		setPrev(cash);
		clearTimeout(timer.current);
		timer.current = setTimeout(() => setDelta(null), 2400);
		return () => clearTimeout(timer.current);
	}, [cash, prev]);

	const fmt = (n: number) => n.toLocaleString('en-US');
	const gain = delta !== null && delta > 0;
	const loss = delta !== null && delta < 0;

	return (
		<span className="inline-flex items-center gap-1.5 font-mono">
			<span
				className={`font-semibold transition-colors ${
					gain ? 'text-green-700' : loss ? 'text-red-700' : 'text-slate-800'
				}`}
			>
				৳{fmt(cash)}
			</span>
			{delta !== null && delta !== 0 && (
				<span
					className={`anim-log-in rounded-full px-1.5 text-xs font-bold ${
						gain ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
					}`}
				>
					{gain ? `+${fmt(delta)}` : fmt(delta)}
				</span>
			)}
		</span>
	);
}
